// Generated by CoffeeScript 1.7.1
(function() {
  var ScrollFader;

  ScrollFader = (function() {
    function ScrollFader(dom) {
      var scrollHandler;
      this.dom = dom;
      scrollHandler = (function(_this) {
        return function(event) {
          return _this.setOpacity(jQuery(window).scrollTop());
        };
      })(this);
      jQuery(window).on('wheel', scrollHandler);
    }

    ScrollFader.prototype.setOpacity = function(y) {
      var maxY, minY, opacity;
      minY = 0;
      maxY = 200;
      opacity = y / (maxY - minY);
      return jQuery(this.dom).css({
        opacity: opacity
      });
    };

    return ScrollFader;

  })();

  jQuery('[data-scroll-fader]').each(function() {
    return new ScrollFader(this);
  });

}).call(this);
